USE [master]
GO
/****** Object:  Database [MusicAI]    Script Date: 2025/6/8 16:57:04 ******/
CREATE DATABASE [MusicAI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MusicAI', FILENAME = N'<MSSQL_DATA_DIR>\MusicAI.mdf , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MusicAI_log', FILENAME = N'<MSSQL_DATA_DIR>\MusicAI_log.ldf , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MusicAI] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicAI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MusicAI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MusicAI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MusicAI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MusicAI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MusicAI] SET ARITHABORT OFF 
GO
ALTER DATABASE [MusicAI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MusicAI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MusicAI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MusicAI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MusicAI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MusicAI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MusicAI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MusicAI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MusicAI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MusicAI] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MusicAI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MusicAI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MusicAI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MusicAI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MusicAI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MusicAI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MusicAI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MusicAI] SET RECOVERY FULL 
GO
ALTER DATABASE [MusicAI] SET  MULTI_USER 
GO
ALTER DATABASE [MusicAI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MusicAI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MusicAI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MusicAI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MusicAI] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MusicAI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MusicAI', N'ON'
GO
ALTER DATABASE [MusicAI] SET QUERY_STORE = ON
GO
ALTER DATABASE [MusicAI] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [MusicAI]
GO
/****** Object:  Table [dbo].[RecentPlays]    Script Date: 2025/6/8 16:57:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecentPlays](
	[RecentPlayID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[UploadedSongID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RecentPlayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SingerStyles]    Script Date: 2025/6/8 16:57:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SingerStyles](
	[SingerStyleID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[FeaturePath] [nvarchar](500) NULL,
	[IndexPath] [nvarchar](500) NULL,
 CONSTRAINT [PK_SingerStyles] PRIMARY KEY CLUSTERED 
(
	[SingerStyleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SingerStyles_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserFavorites]    Script Date: 2025/6/8 16:57:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserFavorites](
	[FavoriteID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[UploadedSongID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FavoriteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2025/6/8 16:57:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[SignupDate] [datetime2](3) NOT NULL,
	[ResetCode] [nvarchar](6) NULL,
	[ResetCodeExpires] [datetime2](3) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Users_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Users_Username] UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserUploadedSongs]    Script Date: 2025/6/8 16:57:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserUploadedSongs](
	[UploadedSongID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[OriginalFileName] [nvarchar](255) NOT NULL,
	[StoredFilePath] [nvarchar](500) NOT NULL,
	[FileType] [nvarchar](10) NOT NULL,
	[DurationSeconds] [int] NULL,
	[FileHash] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_UserUploadedSongs] PRIMARY KEY CLUSTERED 
(
	[UploadedSongID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [UX_RecentPlays_User_Song]    Script Date: 2025/6/8 16:57:05 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_RecentPlays_User_Song] ON [dbo].[RecentPlays]
(
	[UserID] ASC,
	[UploadedSongID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_UserFavorites_User_Song]    Script Date: 2025/6/8 16:57:05 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_UserFavorites_User_Song] ON [dbo].[UserFavorites]
(
	[UserID] ASC,
	[UploadedSongID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_SignupDate]  DEFAULT (getdate()) FOR [SignupDate]
GO
ALTER TABLE [dbo].[UserUploadedSongs] ADD  DEFAULT ('') FOR [FileHash]
GO
ALTER TABLE [dbo].[RecentPlays]  WITH CHECK ADD  CONSTRAINT [FK_RecentPlays_UploadedSong] FOREIGN KEY([UploadedSongID])
REFERENCES [dbo].[UserUploadedSongs] ([UploadedSongID])
GO
ALTER TABLE [dbo].[RecentPlays] CHECK CONSTRAINT [FK_RecentPlays_UploadedSong]
GO
ALTER TABLE [dbo].[RecentPlays]  WITH CHECK ADD  CONSTRAINT [FK_RecentPlays_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[RecentPlays] CHECK CONSTRAINT [FK_RecentPlays_Users]
GO
ALTER TABLE [dbo].[UserFavorites]  WITH CHECK ADD  CONSTRAINT [FK_UserFavorites_UploadedSong] FOREIGN KEY([UploadedSongID])
REFERENCES [dbo].[UserUploadedSongs] ([UploadedSongID])
GO
ALTER TABLE [dbo].[UserFavorites] CHECK CONSTRAINT [FK_UserFavorites_UploadedSong]
GO
ALTER TABLE [dbo].[UserFavorites]  WITH CHECK ADD  CONSTRAINT [FK_UserFavorites_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[UserFavorites] CHECK CONSTRAINT [FK_UserFavorites_Users]
GO
ALTER TABLE [dbo].[UserUploadedSongs]  WITH CHECK ADD  CONSTRAINT [FK_UserUploadedSongs_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserUploadedSongs] CHECK CONSTRAINT [FK_UserUploadedSongs_Users]
GO
/****** Object:  StoredProcedure [dbo].[AddOrUpdateRecentPlay]    Script Date: 2025/6/8 16:57:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[AddOrUpdateRecentPlay]
    @UserID INT,
    @UploadedSongID INT,
    @LastPlatform NVARCHAR(50) = NULL,    -- 可选参数
    @LastDevice NVARCHAR(50) = NULL       -- 可选参数
AS
BEGIN
    SET NOCOUNT ON;
    MERGE INTO RecentPlays AS target
    USING (SELECT @UserID AS UserID, @UploadedSongID AS UploadedSongID) AS source
    ON target.UserID = source.UserID AND target.UploadedSongID = source.UploadedSongID
    WHEN MATCHED THEN
        UPDATE SET PlayedAt = GETDATE(), 
                   PlayCount = PlayCount + 1,
                   LastPlatform = ISNULL(@LastPlatform, LastPlatform),
                   LastDevice = ISNULL(@LastDevice, LastDevice)
    WHEN NOT MATCHED THEN
        INSERT (UserID, UploadedSongID, PlayedAt, PlayCount, LastPlatform, LastDevice)
        VALUES (@UserID, @UploadedSongID, GETDATE(), 1, @LastPlatform, @LastDevice);
END
GO
USE [master]
GO
ALTER DATABASE [MusicAI] SET  READ_WRITE 
GO
